config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
  namespace :themes do
    resources :paraphrases, only: [:show, :new, :create, :destroy], shallow: true
  end

  resources :users, only: :show
  
  resources :paraphrases do
    member do
      get 'add'
    end
    resources :comments, only: :create, shallow: true
  end

  resources :themes



end

app/controllers/paraphrases_controller.rb
class ParaphrasesController < ApplicationController
  def index
    if user_signed_in?
      user = User.find(current_user[:id])
      @nickname = user.nickname
    end
    @theme = Theme.includes(:user).order("created_at DESC").page(params[:page]).per(4)
  end

  def new
    if user_signed_in?
      user = User.find(current_user[:id])
      @nickname = user.nickname
    end
    @themes = Theme.order("RAND()").limit(1)
    @paraphrase = @themes[0].paraphrases.new
  end

  def add
    if user_signed_in?
      user = User.find(current_user[:id])
      @nickname = user.nickname
    end
    @theme = Theme.find(params[:id])
    @paraphrase = Paraphrase.new
  end

  def create
    if user_signed_in?
      @paraphrase = Paraphrase.new(sentence_params)
      @theme = Theme.find(@paraphrase[:theme_id])
      if @paraphrase.save
      else
        redirect_to root_path
      end
    else
      redirect_to new_user_registration_path
    end
    images = ["savanna.jpg", "sunset.jpg", "water_house.jpg", "car_road.jpg", "forest_road.jpg", "lake.jpg", "ocean.jpg", "rail_road.jpg"]
    @image = images.sample    
  end

  private
  def sentence_params
    params.require(:paraphrase).permit(
      :answer,
      :theme_id,
      :paraphrase_id
      ).merge(user_id: current_user.id)
  end

end

app/controllers/themes/paraphrases_controller.rb
class Themes::ParaphrasesController < ApplicationController
  before_action :set_theme, only: [:show]

  def show
    if user_signed_in?
      user = User.find(current_user[:id])
      @nickname = user.nickname
    end
    @themes = Theme.order("RAND()").limit(1)
    @theme = Theme.find(params[:id])
    @comment = Comment.new
    @comments = @paraphrase.comments.includes(:user).order("created_at DESC").page(params[:page]).per(12)
  end

  def set_theme
    theme = Theme.find(params[:id])
    @paraphrase = theme.paraphrases[0]
  end

end

app/helpers/paraphrases_helper.rb
module ParaphrasesHelper
end

app/helpers/themes/paraphrases_helper.rb
module Themes::ParaphrasesHelper
end

app/views/paraphrases/add.html.haml
= render "users/header"
.new_sentence
  = form_with model: @paraphrase, local: true, class: 'new_sentence__main' do |f|
    .new_sentence__main__theme
      .new_sentence__main__theme__header
      .new_sentence__main__theme__body
        .new_sentence__main__theme__body__text
          = @theme.question
        .new_sentence__main__theme__body__image
          = image_tag "BigUnder.png", size:"400x100"
    .new_sentence__main__answer
      .new_sentence__main__answer__header
        = f.text_field :answer, type: "text", placeholder:"  paraphrase?", class: "new_sentence__main__answer__header__text"
        = f.hidden_field :theme_id, value: "#{@theme.id}"
      .new_sentence__main__answer__body
        = f.submit "O K !" ,class: "new_sentence__main__answer__body__button" 

app/views/paraphrases/create.html.haml
.result
  .result__main
    = image_tag "#{@image}", class: "result__main__background"
    .result__main__top
      .result__main__top__comment
        Nice paraphrase !
      .result__main__top__text
        .result__main__top__text__theme
          This time's theme
          .question
            = @theme.question
        .result__main__top__text__paraphrase
          Your paraphrase
          .answer
            = @paraphrase.answer
    .result__main__body
    .result__main__list
      = link_to "more", new_paraphrase_path, class: "result__main__list__more"
      = link_to "past", themes_path, class: "result__main__list__past"
      = link_to "title", root_path, class: "result__main__list__title"

app/views/paraphrases/new.html.haml
= render "users/header"
.new_sentence
  = form_with model: @paraphrase, local: true, class: 'new_sentence__main' do |f|
    .new_sentence__main__theme
      .new_sentence__main__theme__header
        
      .new_sentence__main__theme__body
        .new_sentence__main__theme__body__text
          = @themes[0].question
        .new_sentence__main__theme__body__image
          = image_tag "BigUnder.png", size:"400x100"
    .new_sentence__main__answer
      .new_sentence__main__answer__header
        = f.text_field :answer, type: "text", placeholder:"  paraphrase?", class: "new_sentence__main__answer__header__text"
        = f.hidden_field :theme_id, value: "#{@themes[0].id}"
      .new_sentence__main__answer__body
        = f.submit "O K !" ,class: "new_sentence__main__answer__body__button" 

app/views/paraphrases/show.html.haml
= render "users/header"
.show_paraphrase
  .show_paraphrase__main
    = link_to "< back", paraphrases_path
    .show_paraphrase__main__title
    .show_paraphrase__main__content
      .show_paraphrase__main__content__answer
        = @paraphrase.answer
      .show_paraphrase__main__content__comments
        %h4 ＜コメント一覧＞
        - if @comments
          - @comments.each do |comment|
            %p
              %strong
                = link_to comment.user.nickname, "/users/#{comment.user_id}"
                ：
                = comment.text
  .show_paraphrase__comments
    - if user_signed_in?
      = form_with model: [@paraphrase, @comment], local: true, id: "new_comment" do |f|
        = f.text_area :text, placeholder: "コメントする" , rows: "2", class: "textbox"
        = f.submit "SEND", class: "form__submit"
    - else
      %strong
        %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※