config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
  namespace :themes do
    resources :paraphrases, only: [:show, :new, :create, :destroy], shallow: true
  end

  resources :users, only: :show
  
  resources :paraphrases do
    member do
      get 'add'
    end
    resources :comments, only: :create, shallow: true
  end

  resources :themes



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :themes
  has_many :paraphrases
  has_many :comments
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   redirect_to root_path
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if user_signed_in?
      user = User.find(current_user[:id])
      @nickname = user.nickname
    end
    @themes = Theme.order("RAND()").limit(1)
  end

  def show
    if user_signed_in?
      user = User.find(current_user[:id])
      @nickname = user.nickname
    end
    @themes = Theme.order("RAND()").limit(1)
    @theme = user.themes.page(params[:page]).per(5).order("created_at DESC")
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_add.html.haml
.add
  = link_to new_theme_path, class: 'add__button' do
    .add__button__name
      Add theme?

app/views/users/_header.html.haml
.header
  .header__container
    .header__container__logo
      = link_to "English Paraphrase", root_path, class: "icon"
    - if @themes.present? && user_signed_in?
      .header__container__phrase
        .header__container__phrase__info
          Today's phrase
        = link_to @themes[0].question, add_paraphrase_path(@themes[0]), class: "header__container__phrase__text"
      .header__container__mypage
        .header__container__mypage__nickname
          = @nickname
        .header__container__mypage__button
          = link_to "My page", user_path(current_user.id), class: "icon"

    - elsif user_signed_in?
      .header__container__phrase
        = link_to "好きな言葉を入れてみよう", new_theme_path, class: "header__container__phrase__text"
      .header__container__mypage
        .header__container__mypage__nickname
          = @nickname
        .header__container__mypage__button
          = link_to "my page", user_path(current_user.id), class: "icon"

    - else
      .header__container__phrase
        登録してみよう！👉
      .header__container__auth
        = link_to "Sign up", new_user_registration_path, class: "header__container__auth__signup" 
        = link_to "Sign in", new_user_session_path, class: "header__container__auth__signin" 

app/views/users/_main.html.haml
.main
  .main__container
    .main__container__background
      = video_tag 'overhead-view.mp4', autoplay: true, poster: "overhead-view.jpg", muted: true, controls: true, loop:true, preload: true, class: "main__container__background__movie"
    .main__container__title
      English Paraphrase
    .main__container__view
    .main__container__menu
    - if @themes.present?
      = link_to new_paraphrase_path, class: 'main__container__menu__go' do
        Let's paraphrase !
      = link_to themes_path, class: 'main__container__menu__past' do
        Past paraphrases
    - else
      = link_to themes_path, class: 'main__container__menu__only' do
        Past paraphrases

app/views/users/index.html.haml
.wrapper
 = render "header"
 = render "main"

app/views/users/show.html.haml
= render "header"
= render "add"
.mypage_logout
  = link_to "Log out", destroy_user_session_path, method: :delete, class: "mypage_logout__button"
.theme_sentence
  .theme_sentence__main
    - @theme.each do |theme|
      .theme_sentence__main__content
        - if theme.paraphrases.present?
          = link_to "comments here !", themes_paraphrase_path(theme), class: "theme_sentence__main__content__button"
        - else
          = link_to "no paraphrase...add?", add_paraphrase_path(theme), class: "theme_sentence__main__content__button"
        = link_to 'DELETE', "/themes/#{theme.id}", method: :delete ,class: "delete"
        .theme_sentence__main__content__theme
          = theme.question
        .theme_sentence__main__content__phrase
          - theme.paraphrases.first(3).each do |paraphrase|
            .theme_sentence__main__content__phrase__text
              = paraphrase.answer